# 🚀 Beta Deployment Script
# Deploys the beta wireframe to Firebase Hosting
# Excludes /dev-dash route from production

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  S.H.A.T. Beta Deployment Script" -ForegroundColor Cyan
Write-Host "  Version: v0.9 - Beta Wireframe" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Clean previous build
Write-Host "[1/5] Cleaning previous build..." -ForegroundColor Yellow
if (Test-Path "dist") {
    Remove-Item -Recurse -Force "dist"
    Write-Host "✓ Cleaned dist folder" -ForegroundColor Green
} else {
    Write-Host "✓ No previous build to clean" -ForegroundColor Green
}
Write-Host ""

# Step 2: Verify environment files exist
Write-Host "[2/5] Verifying environment configuration..." -ForegroundColor Yellow
if (Test-Path ".env.production") {
    $prodEnv = Get-Content ".env.production" -Raw
    if ($prodEnv -match "VITE_ENABLE_DEV_ROUTES=false") {
        Write-Host "✓ Production environment configured correctly" -ForegroundColor Green
        Write-Host "  /dev-dash will be EXCLUDED from deployment" -ForegroundColor Gray
    } else {
        Write-Host "⚠ WARNING: Dev routes may not be disabled!" -ForegroundColor Red
    }
} else {
    Write-Host "! .env.production not found - creating it..." -ForegroundColor Yellow
    @"
# Production Environment Configuration
# Auto-generated by deploy-beta.ps1

# Disable development-only routes in production
VITE_ENABLE_DEV_ROUTES=false
"@ | Out-File -FilePath ".env.production" -Encoding utf8
    Write-Host "✓ Created .env.production (dev routes disabled)" -ForegroundColor Green
    Write-Host "  /dev-dash will be EXCLUDED from deployment" -ForegroundColor Gray
}
Write-Host ""

# Step 3: Build production bundle
Write-Host "[3/5] Building production bundle..." -ForegroundColor Yellow
npm run build
if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Build failed! Check errors above." -ForegroundColor Red
    exit 1
}
Write-Host "✓ Build completed successfully" -ForegroundColor Green
Write-Host ""

# Step 4: Preview build locally (optional)
Write-Host "[4/5] Local preview..." -ForegroundColor Yellow
$preview = Read-Host "Preview build locally before deploying? (y/n)"
if ($preview -eq "y" -or $preview -eq "Y") {
    Write-Host "Starting local preview server..." -ForegroundColor Cyan
    Write-Host "Press Ctrl+C to stop and continue with deployment" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Test these URLs:" -ForegroundColor Cyan
    Write-Host "  /dash       - Coming Soon page" -ForegroundColor White
    Write-Host "  /beta-dash  - Beta wireframe (SHOULD WORK)" -ForegroundColor Green
    Write-Host "  /dev-dash   - Dev dashboard (SHOULD 404)" -ForegroundColor Red
    Write-Host ""
    npm run preview
}
Write-Host ""

# Step 5: Deploy to Firebase
Write-Host "[5/5] Deploying to Firebase Hosting..." -ForegroundColor Yellow
$deploy = Read-Host "Proceed with deployment? (y/n)"
if ($deploy -eq "y" -or $deploy -eq "Y") {
    firebase deploy --only hosting
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Green
        Write-Host "  ✓ Deployment Successful!" -ForegroundColor Green
        Write-Host "========================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "Live URLs:" -ForegroundColor Cyan
        Write-Host "  Coming Soon:    https://space-haven-analysis-terminal-dashboard.web.app/dash" -ForegroundColor White
        Write-Host "  Beta Wireframe: https://space-haven-analysis-terminal-dashboard.web.app/beta-dash" -ForegroundColor Green
        Write-Host "  Data Dictionary: https://space-haven-analysis-terminal-dashboard.web.app/data" -ForegroundColor White
        Write-Host ""
        Write-Host "Next Steps:" -ForegroundColor Yellow
        Write-Host "  1. Test all routes on live site" -ForegroundColor Gray
        Write-Host "  2. Verify /dev-dash returns 404" -ForegroundColor Gray
        Write-Host "  3. Check Firebase Analytics dashboard" -ForegroundColor Gray
        Write-Host "  4. Monitor for errors in browser console" -ForegroundColor Gray
        Write-Host ""
    } else {
        Write-Host ""
        Write-Host "✗ Deployment failed!" -ForegroundColor Red
        Write-Host "Check Firebase authentication and project configuration" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "Deployment cancelled." -ForegroundColor Yellow
}
